### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by CalvinMcGee** [EdgecaseInc/wercker-step-install-aws-cli#3]
Is there documentation around example usage for this step? How do you use it in your wercker.yml?

**Comment by andrew-templeton** [comment]
The example in the README is a complete example.

**Comment by CalvinMcGee** [comment]
I mean for instance if would like to use s3 sync, how would you write that in the wercker.yml?

**Comment by andrew-templeton** [comment]
The AWS CLI will be installed in the environment/pipeline after this step. Follow their documentation or the S3 sync wrecker step documentation. This step is not responsible for your sync. Please close this issue as it is not an issue with the repository nor the documentation for the tool.

**Comment by jlgoolsbee** [comment]
After including this step in your _wercker.yml_, direct usage of the AWS CLI will be possible via a `script` block; something like the following:

``` yaml
- script:
    name: Sync with S3
    code: |-
      aws s3 sync ./ s3://bucketname/path/to/folder
```
