### ISSUE TITLE
Missing aws_secret_access_key

### ISSUE THREAD

**Issue by spaghettifunk** [EdgecaseInc/wercker-step-install-aws-cli#8]
I am having this issue where the step cannot find my aws_secret.  My step looks like the follwing:

```
deploy:
  steps:
  - edgecaseadmin/install-aws-cli:
      key: $AWS_KEY
      secret: $AWS_SECRET
      region: $AWS_REGION
  - script:
      name: "Push application build to S3"
      code: |
          aws s3 cp $WERCKER_OUTPUT_DIR/etl.jar s3://test/emr/etl.jar
```
Although Wercker prints this output:
```
export WERCKER_STEP_ROOT="/pipeline/script-198899c3-d2ce-4b03-9a8d-4d24646d0f96"
export WERCKER_STEP_ID="script-198899c3-d2ce-4b03-9a8d-4d24646d0f96"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="script"
export WERCKER_REPORT_NUMBERS_FILE="/report/script-198899c3-d2ce-4b03-9a8d-4d24646d0f96/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/script-198899c3-d2ce-4b03-9a8d-4d24646d0f96/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/script-198899c3-d2ce-4b03-9a8d-4d24646d0f96/artifacts"
source "/pipeline/script-198899c3-d2ce-4b03-9a8d-4d24646d0f96/run.sh" < /dev/null

Partial credentials found in shared-credentials-file, missing: aws_secret_access_key
```

I followed the README and added as Environmental Variables the ```AWS_KEY```, ```AWS_SECRET``` and ```AWS_REGION```. Because they are credentials, they are set as ```protected```. My credentials can upload to my S3 bucket because if I ran the ```aws cli``` it works fine. Any idea ?
